// Generated by CoffeeScript 1.7.1
(function() {
  new AppView({
    model: new App()
<<<<<<< HEAD
  }).$el.appendTo('body');
=======
  }).$el.appendTo('.bottom');
>>>>>>> pair_programming

}).call(this);

//# sourceMappingURL=main.map
